[2023-05-01T09:35:49.106+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-05-01T09:35:49.196+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark_process_data_12.spark_job_clean_data_12 manual__2023-05-01T09:34:37.921066+00:00 [queued]>
[2023-05-01T09:35:49.248+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark_process_data_12.spark_job_clean_data_12 manual__2023-05-01T09:34:37.921066+00:00 [queued]>
[2023-05-01T09:35:49.249+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T09:35:49.250+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-05-01T09:35:49.250+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T09:35:49.341+0000] {taskinstance.py:1383} INFO - Executing <Task(SparkSubmitOperator): spark_job_clean_data_12> on 2023-05-01 09:34:37.921066+00:00
[2023-05-01T09:35:49.354+0000] {standard_task_runner.py:54} INFO - Started process 983 to run task
[2023-05-01T09:35:49.364+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_process_data_12', 'spark_job_clean_data_12', 'manual__2023-05-01T09:34:37.921066+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/spark_process_scheduler.py', '--cfg-path', '/tmp/tmpmqt85uhg']
[2023-05-01T09:35:49.366+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask spark_job_clean_data_12
[2023-05-01T09:35:49.369+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/spark_process_scheduler.py
[2023-05-01T09:35:49.694+0000] {task_command.py:384} INFO - Running <TaskInstance: spark_process_data_12.spark_job_clean_data_12 manual__2023-05-01T09:34:37.921066+00:00 [running]> on host 041de89279d2
[2023-05-01T09:35:49.705+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-01T09:35:49.964+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=pioneer22022001@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_process_data_12
AIRFLOW_CTX_TASK_ID=spark_job_clean_data_12
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T09:34:37.921066+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-01T09:34:37.921066+00:00
[2023-05-01T09:35:49.998+0000] {base.py:71} INFO - Using connection ID 'other_spark_local' for task execution.
[2023-05-01T09:35:50.004+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master spark://4765e3f6cf67:7077 --conf spark.master=spark://4765e3f6cf67:7077 --name spark_clean_data --verbose /opt/spark/app/preprocess_data.py
[2023-05-01T09:35:50.053+0000] {spark_submit.py:490} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-05-01T09:35:53.867+0000] {spark_submit.py:490} INFO - Using properties file: null
[2023-05-01T09:35:54.565+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-01T09:35:54.651+0000] {spark_submit.py:490} INFO - Parsed arguments:
[2023-05-01T09:35:54.651+0000] {spark_submit.py:490} INFO - master                  spark://4765e3f6cf67:7077
[2023-05-01T09:35:54.652+0000] {spark_submit.py:490} INFO - deployMode              null
[2023-05-01T09:35:54.653+0000] {spark_submit.py:490} INFO - executorMemory          null
[2023-05-01T09:35:54.653+0000] {spark_submit.py:490} INFO - executorCores           null
[2023-05-01T09:35:54.654+0000] {spark_submit.py:490} INFO - totalExecutorCores      null
[2023-05-01T09:35:54.654+0000] {spark_submit.py:490} INFO - propertiesFile          null
[2023-05-01T09:35:54.655+0000] {spark_submit.py:490} INFO - driverMemory            null
[2023-05-01T09:35:54.655+0000] {spark_submit.py:490} INFO - driverCores             null
[2023-05-01T09:35:54.656+0000] {spark_submit.py:490} INFO - driverExtraClassPath    null
[2023-05-01T09:35:54.656+0000] {spark_submit.py:490} INFO - driverExtraLibraryPath  null
[2023-05-01T09:35:54.657+0000] {spark_submit.py:490} INFO - driverExtraJavaOptions  null
[2023-05-01T09:35:54.658+0000] {spark_submit.py:490} INFO - supervise               false
[2023-05-01T09:35:54.658+0000] {spark_submit.py:490} INFO - queue                   null
[2023-05-01T09:35:54.659+0000] {spark_submit.py:490} INFO - numExecutors            null
[2023-05-01T09:35:54.659+0000] {spark_submit.py:490} INFO - files                   null
[2023-05-01T09:35:54.660+0000] {spark_submit.py:490} INFO - pyFiles                 null
[2023-05-01T09:35:54.661+0000] {spark_submit.py:490} INFO - archives                null
[2023-05-01T09:35:54.661+0000] {spark_submit.py:490} INFO - mainClass               null
[2023-05-01T09:35:54.662+0000] {spark_submit.py:490} INFO - primaryResource         file:/opt/spark/app/preprocess_data.py
[2023-05-01T09:35:54.663+0000] {spark_submit.py:490} INFO - name                    spark_clean_data
[2023-05-01T09:35:54.663+0000] {spark_submit.py:490} INFO - childArgs               []
[2023-05-01T09:35:54.664+0000] {spark_submit.py:490} INFO - jars                    null
[2023-05-01T09:35:54.665+0000] {spark_submit.py:490} INFO - packages                null
[2023-05-01T09:35:54.665+0000] {spark_submit.py:490} INFO - packagesExclusions      null
[2023-05-01T09:35:54.666+0000] {spark_submit.py:490} INFO - repositories            null
[2023-05-01T09:35:54.671+0000] {spark_submit.py:490} INFO - verbose                 true
[2023-05-01T09:35:54.672+0000] {spark_submit.py:490} INFO - 
[2023-05-01T09:35:54.673+0000] {spark_submit.py:490} INFO - Spark properties used, including those specified through
[2023-05-01T09:35:54.674+0000] {spark_submit.py:490} INFO - --conf and those from the properties file null:
[2023-05-01T09:35:54.674+0000] {spark_submit.py:490} INFO - (spark.master,spark://4765e3f6cf67:7077)
[2023-05-01T09:35:54.675+0000] {spark_submit.py:490} INFO - 
[2023-05-01T09:35:54.676+0000] {spark_submit.py:490} INFO - 
[2023-05-01T09:35:55.916+0000] {spark_submit.py:490} INFO - Main class:
[2023-05-01T09:35:55.917+0000] {spark_submit.py:490} INFO - org.apache.spark.deploy.PythonRunner
[2023-05-01T09:35:55.918+0000] {spark_submit.py:490} INFO - Arguments:
[2023-05-01T09:35:55.919+0000] {spark_submit.py:490} INFO - file:/opt/spark/app/preprocess_data.py
[2023-05-01T09:35:55.919+0000] {spark_submit.py:490} INFO - null
[2023-05-01T09:35:55.925+0000] {spark_submit.py:490} INFO - Spark config:
[2023-05-01T09:35:55.926+0000] {spark_submit.py:490} INFO - (spark.app.name,spark_clean_data)
[2023-05-01T09:35:55.926+0000] {spark_submit.py:490} INFO - (spark.submit.pyFiles,)
[2023-05-01T09:35:55.927+0000] {spark_submit.py:490} INFO - (spark.submit.deployMode,client)
[2023-05-01T09:35:55.928+0000] {spark_submit.py:490} INFO - (spark.master,spark://4765e3f6cf67:7077)
[2023-05-01T09:35:55.928+0000] {spark_submit.py:490} INFO - Classpath elements:
[2023-05-01T09:35:55.929+0000] {spark_submit.py:490} INFO - 
[2023-05-01T09:35:55.929+0000] {spark_submit.py:490} INFO - 
[2023-05-01T09:35:55.930+0000] {spark_submit.py:490} INFO - 
[2023-05-01T09:35:56.150+0000] {spark_submit.py:490} INFO - python3: can't open file '/opt/spark/app/preprocess_data.py': [Errno 2] No such file or directory
[2023-05-01T09:35:56.177+0000] {spark_submit.py:490} INFO - log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
[2023-05-01T09:35:56.178+0000] {spark_submit.py:490} INFO - log4j:WARN Please initialize the log4j system properly.
[2023-05-01T09:35:56.178+0000] {spark_submit.py:490} INFO - log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[2023-05-01T09:35:56.301+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-05-01T09:35:56.325+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://4765e3f6cf67:7077 --conf spark.master=spark://4765e3f6cf67:7077 --name spark_clean_data --verbose /opt/spark/app/preprocess_data.py. Error code is: 2.
[2023-05-01T09:35:56.333+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-01T09:35:56.350+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=spark_process_data_12, task_id=spark_job_clean_data_12, execution_date=20230501T093437, start_date=20230501T093549, end_date=20230501T093556
[2023-05-01T09:35:56.395+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/utils/email.py:120: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-05-01T09:35:56.396+0000] {configuration.py:569} WARNING - section/key [smtp/smtp_user] not found in config
[2023-05-01T09:35:56.396+0000] {email.py:229} INFO - Email alerting: attempt 1
[2023-05-01T09:35:56.419+0000] {configuration.py:569} WARNING - section/key [smtp/smtp_user] not found in config
[2023-05-01T09:35:56.420+0000] {email.py:229} INFO - Email alerting: attempt 1
[2023-05-01T09:35:56.421+0000] {taskinstance.py:1914} ERROR - Failed to send email to: ['pioneer22022001@gmail.com']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1457, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1603, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1664, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://4765e3f6cf67:7077 --conf spark.master=spark://4765e3f6cf67:7077 --name spark_clean_data --verbose /opt/spark/app/preprocess_data.py. Error code is: 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2311, in email_alert
    send_email(task.email, subject, html_content)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1912, in handle_failure
    self.email_alert(error, task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2313, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-05-01T09:35:56.471+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task spark_job_clean_data_12 (Cannot execute: spark-submit --master spark://4765e3f6cf67:7077 --conf spark.master=spark://4765e3f6cf67:7077 --name spark_clean_data --verbose /opt/spark/app/preprocess_data.py. Error code is: 2.; 983)
[2023-05-01T09:35:56.529+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-05-01T09:35:56.667+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
