[2023-05-01T09:31:48.570+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-05-01T09:31:48.622+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark_process_data_12.spark_job_clean_data_12 manual__2023-05-01T09:30:36.881676+00:00 [queued]>
[2023-05-01T09:31:48.674+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark_process_data_12.spark_job_clean_data_12 manual__2023-05-01T09:30:36.881676+00:00 [queued]>
[2023-05-01T09:31:48.675+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T09:31:48.675+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-05-01T09:31:48.676+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T09:31:48.742+0000] {taskinstance.py:1383} INFO - Executing <Task(SparkSubmitOperator): spark_job_clean_data_12> on 2023-05-01 09:30:36.881676+00:00
[2023-05-01T09:31:48.753+0000] {standard_task_runner.py:54} INFO - Started process 729 to run task
[2023-05-01T09:31:48.763+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_process_data_12', 'spark_job_clean_data_12', 'manual__2023-05-01T09:30:36.881676+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/spark_process_scheduler.py', '--cfg-path', '/tmp/tmpq37hrddy']
[2023-05-01T09:31:48.764+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask spark_job_clean_data_12
[2023-05-01T09:31:48.767+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/spark_process_scheduler.py
[2023-05-01T09:31:49.051+0000] {task_command.py:384} INFO - Running <TaskInstance: spark_process_data_12.spark_job_clean_data_12 manual__2023-05-01T09:30:36.881676+00:00 [running]> on host 041de89279d2
[2023-05-01T09:31:49.060+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-01T09:31:49.359+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=pioneer22022001@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_process_data_12
AIRFLOW_CTX_TASK_ID=spark_job_clean_data_12
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T09:30:36.881676+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-01T09:30:36.881676+00:00
[2023-05-01T09:31:49.412+0000] {spark_submit.py:218} INFO - Could not load connection string other_spark_local, defaulting to yarn
[2023-05-01T09:31:49.418+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=spark://b2fb9a2a1e2d:7077 --name spark_clean_data --verbose /opt/spark/app/preprocess_data.py
[2023-05-01T09:31:49.458+0000] {spark_submit.py:490} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-05-01T09:31:53.894+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-01T09:31:53.982+0000] {spark_submit.py:490} INFO - Using properties file: null
[2023-05-01T09:31:54.563+0000] {spark_submit.py:490} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-05-01T09:31:54.565+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2023-05-01T09:31:54.565+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2023-05-01T09:31:54.566+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2023-05-01T09:31:54.567+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2023-05-01T09:31:54.567+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1026)
[2023-05-01T09:31:54.568+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1026)
[2023-05-01T09:31:54.568+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2023-05-01T09:31:54.569+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
[2023-05-01T09:31:54.570+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
[2023-05-01T09:31:54.570+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-05-01T09:31:54.639+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-05-01T09:31:54.662+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=spark://b2fb9a2a1e2d:7077 --name spark_clean_data --verbose /opt/spark/app/preprocess_data.py. Error code is: 1.
[2023-05-01T09:31:54.672+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-01T09:31:54.694+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=spark_process_data_12, task_id=spark_job_clean_data_12, execution_date=20230501T093036, start_date=20230501T093148, end_date=20230501T093154
[2023-05-01T09:31:54.739+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/utils/email.py:120: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-05-01T09:31:54.740+0000] {configuration.py:569} WARNING - section/key [smtp/smtp_user] not found in config
[2023-05-01T09:31:54.741+0000] {email.py:229} INFO - Email alerting: attempt 1
[2023-05-01T09:31:54.763+0000] {configuration.py:569} WARNING - section/key [smtp/smtp_user] not found in config
[2023-05-01T09:31:54.764+0000] {email.py:229} INFO - Email alerting: attempt 1
[2023-05-01T09:31:54.766+0000] {taskinstance.py:1914} ERROR - Failed to send email to: ['pioneer22022001@gmail.com']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1457, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1603, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1664, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=spark://b2fb9a2a1e2d:7077 --name spark_clean_data --verbose /opt/spark/app/preprocess_data.py. Error code is: 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2311, in email_alert
    send_email(task.email, subject, html_content)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1912, in handle_failure
    self.email_alert(error, task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2313, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-05-01T09:31:54.828+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task spark_job_clean_data_12 (Cannot execute: spark-submit --master yarn --conf spark.master=spark://b2fb9a2a1e2d:7077 --name spark_clean_data --verbose /opt/spark/app/preprocess_data.py. Error code is: 1.; 729)
[2023-05-01T09:31:54.867+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-05-01T09:31:54.980+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
